ignored:
  - FAKE_DL3003
  - DL3006
  
trustedRegistries:
  - gcr.io
  - docker.io
  - quay.io
  - registry.access.redhat.com
  - docker-na-public.artifactory.swg-devops.com/hyc-cloud-private-edge-docker-local
