# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   creationTimestamp: null
#   name: ibm-cert-manager-access
#   labels:
#     app.kubernetes.io/instance: ibm-cert-manager-operator
#     app.kubernetes.io/managed-by: ibm-cert-manager-operator
#     app.kubernetes.io/name: cert-manager
# rules:
# - apiGroups: 
#   - certmanager.k8s.io
#   resources:
#   - certificates
#   - issuers
#   verbs:
#   - create
#   - update
#   - patch
#   - delete
#   - get
