channels:
- currentCSV: ibm-cert-manager-operator.v3.7.1
  name: dev
- currentCSV: ibm-cert-manager-operator.v3.7.0
  name: beta
- currentCSV: ibm-cert-manager-operator.v3.6.3
  name: stable-v1
defaultChannel: stable-v1
packageName: ibm-cert-manager-operator
