
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.7.0
  creationTimestamp: null
  name: certmanagerconfigs.operator.ibm.com
spec:
  group: operator.ibm.com
  names:
    kind: CertManagerConfig
    listKind: CertManagerConfigList
    plural: certmanagerconfigs
    singular: certmanagerconfig
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: 'CertManagerConfig is the Schema for the certmanagerconfigs API.
          Documentation For additional details regarding install parameters check:
          https://ibm.biz/icpfs39install. License By installing this product you accept
          the license terms https://ibm.biz/icpfs39license.'
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: CertManagerConfigSpec defines the desired state of CertManager
            properties:
              certManagerCAInjector:
                description: CertManagerCAInjector describes spec for cert-manager-cainjector
                  workload
                properties:
                  resources:
                    description: ResourceRequirements describes the compute resource
                      requirements.
                    properties:
                      limits:
                        additionalProperties:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        description: 'Limits describes the maximum amount of compute
                          resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                        type: object
                      requests:
                        additionalProperties:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        description: 'Requests describes the minimum amount of compute
                          resources required. If Requests is omitted for a container,
                          it defaults to Limits if that is explicitly specified, otherwise
                          to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                        type: object
                    type: object
                type: object
              certManagerController:
                description: CertManagerController describes spec for cert-manager-controller
                  workload
                properties:
                  resources:
                    description: ResourceRequirements describes the compute resource
                      requirements.
                    properties:
                      limits:
                        additionalProperties:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        description: 'Limits describes the maximum amount of compute
                          resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                        type: object
                      requests:
                        additionalProperties:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        description: 'Requests describes the minimum amount of compute
                          resources required. If Requests is omitted for a container,
                          it defaults to Limits if that is explicitly specified, otherwise
                          to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                        type: object
                    type: object
                type: object
              certManagerWebhook:
                description: CertManagerWebhook describes spec for cert-manager-webhook
                  workload
                properties:
                  resources:
                    description: ResourceRequirements describes the compute resource
                      requirements.
                    properties:
                      limits:
                        additionalProperties:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        description: 'Limits describes the maximum amount of compute
                          resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                        type: object
                      requests:
                        additionalProperties:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        description: 'Requests describes the minimum amount of compute
                          resources required. If Requests is omitted for a container,
                          it defaults to Limits if that is explicitly specified, otherwise
                          to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                        type: object
                    type: object
                type: object
              configMapWatcher:
                description: ConfigMapWatcher is not used
                properties:
                  resources:
                    description: ResourceRequirements describes the compute resource
                      requirements.
                    properties:
                      limits:
                        additionalProperties:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        description: 'Limits describes the maximum amount of compute
                          resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                        type: object
                      requests:
                        additionalProperties:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        description: 'Requests describes the minimum amount of compute
                          resources required. If Requests is omitted for a container,
                          it defaults to Limits if that is explicitly specified, otherwise
                          to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/'
                        type: object
                    type: object
                type: object
              disableHostNetwork:
                description: DisableHostNetwork disables
                type: boolean
              enableCertRefresh:
                description: EnableCertRefresh enables the refresh of leaf certificates
                  based on a CA certificate
                type: boolean
              enableWebhook:
                description: Webhook enables the cert-manager-webhook operand
                type: boolean
              imagePostFix:
                description: ImagePostFix describes a string that will be appended
                  to the end of the fully qualified image, e.g. imageRegistry/imageName:imageTagAndPostFix
                type: string
              imageRegistry:
                description: ImageRegistry describes the image registry for the operands,
                  e.g. cert-manager-controller
                type: string
              license:
                description: LicenseAcceptance defines the license specification in
                  CSV
                properties:
                  accept:
                    description: 'Accepting the license - URL: https://ibm.biz/integration-licenses'
                    type: boolean
                  key:
                    description: The license key for this deployment.
                    type: string
                  license:
                    description: The license being accepted where the component has
                      multiple.
                    type: string
                  use:
                    description: The type of license being accepted.
                    type: string
                type: object
              refreshCertsBasedOnCA:
                description: RefreshCertsBasedOnCA is a list of CA certificate names.
                  Leaf certificates created from any of the listed CA will be refreshed
                  when the CA is refreshed
                items:
                  description: CACertificate describes a CA Certfiicate's name and
                    namespace
                  properties:
                    certName:
                      type: string
                    namespace:
                      type: string
                  required:
                  - certName
                  - namespace
                  type: object
                type: array
              resourceNamespace:
                description: ResourceNS describes the cluster-resource-namespace flag
                  for cert-manager-controller operand, which is used to configure
                  the namespace the operand will use for ClusterIssuer secretReferences
                type: string
              version:
                description: Version descibes the version of cert-manager-operator.
                  Changing the value does not change the cert-manager-operator version
                type: string
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: CertManagerConfigStatus defines the observed state of CertManagerConfig
            properties:
              certManagerConfigStatus:
                description: OverallStatus describes whether cert-manager operands
                  have been successfully deployed or not.
                type: string
            required:
            - certManagerConfigStatus
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
